name: Generate GitHub Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Generate Contribution Grid Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AlkaidSTART
          outputs: |
            assets/github-contribution-grid-snake.svg?color_snake=#db2777&color_dots=#ebedf0,#93c5fd,#60a5fa,#3b82f6,#1d4ed8
            assets/github-contribution-grid-snake-dark.svg?color_snake=#00f5ff&color_dots=#161b22,#4c1d95,#7c3aed,#db2777,#f43f5e

      - name: Deploy Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
