name: Generate GitHub Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Generate Contribution Grid Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AlkaidSTART
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#0369a1&color_dots=#ebedf0,#bae6fd,#7dd3fc,#38bdf8,#0284c7
            dist/github-contribution-grid-snake-dark.svg?color_snake=#7dd3fc&color_dots=#161b22,#0c4a6e,#0284c7,#38bdf8,#bae6fd

      - name: Deploy Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
